### ISSUE TITLE
Add -v latest option

### ISSUE THREAD

**Issue by Firstyear** [yaleman/splunk-downloader#2]
A -v latest specifier would be great to allow automatic filtering to the latest version :)

**Comment by yaleman** [comment]
Or you could just `| head -n1`  ? 😄 

It'd take a pretty big rewrite of the whole thing to be able to identify "latest" across all the various dimensions... 😭

**Comment by Firstyear** [comment]
If your sorting already works to put the latest as head, couldn't you tweak or use fact somehow?

**Comment by yaleman** [comment]
It's only a blind string sort, ignores cpu/os/filetype etc...

https://github.com/yaleman/splunk-downloader/blob/07274301a9ba4bd4dfb0ae49e52fafc090a1bd70/splunk-downloader.py#L202
